name: CI

on:
  schedule:
    - cron: '0 1 1 * *'
  pull_request:
  push:
    branches:
      - main
    tags:
      - '**'
  workflow_run:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME_RW }}
          password: ${{ secrets.DOCKERHUB_PASSWORD_RW }}
      - name: Login to GitHub Packages
        uses: docker/login-action@v2
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
      - name: Get current date
        id: date
        run: |-
          "date=$(date +'%y.%m')" >> $GITHUB_OUTPUT
      - name: Generate Docker meta names
        uses: docker/metadata-action@v4
        id: meta
        with:
          images: ${{ github.repository }},ghcr.io/${{ github.repository }}
          tags: |
            type=ref,event=tag
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}
            type=raw,value=${{ steps.date.outputs.date }},enable=${{ github.event_name == 'schedule' }}
      - name: Build Docker
        uses: docker/build-push-action@v4
        with:
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          context: .
